### ISSUE TITLE
Metadata field title breaking

### ISSUE THREAD

**Issue by alyssafahringer** [omeka-s-themes/cozy#10]
At its widest: 
![screen shot 2016-10-25 at 12 04 22 pm](https://cloud.githubusercontent.com/assets/8807816/19693883/39f88b8c-9aab-11e6-9c49-c238db5e487c.png)

At its narrowest:
![screen shot 2016-10-25 at 12 06 33 pm](https://cloud.githubusercontent.com/assets/8807816/19693964/85cb13c2-9aab-11e6-9e00-e7e2f7f9053a.png)

**Comment by kimisgold** [comment]
The property name breaking should be fixed now.

@alyssafahringer The mobile view looks like an old version of the theme. The dev server should have the latest now, so could you check to see this view has improved?

**Comment by alyssafahringer** [comment]
It does not seem to have improved in Chrome or Firefox. 

In Chrome:
![chrome](https://cloud.githubusercontent.com/assets/8807816/19698295/b519a614-9abc-11e6-83bd-1043d590f7ac.png)

In Firefox: 
![firefox](https://cloud.githubusercontent.com/assets/8807816/19698301/bcc1c612-9abc-11e6-98c7-449a7a4e1756.png)
