### ISSUE TITLE
Vertical scroll disables on Collecting pages when Mapping is active

### ISSUE THREAD

**Issue by mebrett** [omeka-s-themes/cozy#16]
I think the issue is with Cozy, since the problem does not persist across other themes.

If you have a page with a block from the Collecting module, and Mapping is active on the install, then for some reason the vertical scroll for the page stops working. Discovered [by this forum poster](https://forum.omeka.org/t/scrolling-not-working-with-collections-form/8779) and visible on [this page in my test install](http://dev.omeka.org/mebrett/testomekas/s/austen/page/collecting) - current versions of S, Cozy, Mapping, & Collecting

**Comment by kimisgold** [comment]
This was an overreaching style from an unneeded leaflet stylesheet in Mapping, fixed in https://github.com/omeka-s-modules/Mapping/commit/c9176ae7caf1d31e3cb708f4b5d766deef2c3b53.
