### ISSUE TITLE
Test new banner setting

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/cozy#26]
There is now a theme setting that allows users to select a banner image to appear across site views. In additional settings, they can control:

* the maximum height of the banner for both mobile and desktop widths
* whether to match the width to the content or window
* where to position the image within the banner container when the container ratio has a much greater width than height

This is on the `master` branch and should be tested on desktop and mobile browsers.

**Comment by katknow** [comment]
Seems to work well across browsers on desktop and mobile devices. My only question is: should the fix banner to top/center/bottom work on mobile devices as well with the different number of pixels than desktop sites? That's the only thing that potentially could be an issue, but if it's supposed to stay put on mobile then it is good to go!

**Comment by kimisgold** [comment]
Yes, the fix banner to top/center/bottom should behave the same way across both desktop and mobile. Are you seeing a difference?

**Comment by katknow** [comment]
Yes--on mobile, it's continuously fixed to the top regardless of what you choose on the back end.

**Comment by kimisgold** [comment]
Hmmmmmmm this is what I'm seeing on iOS. The banner height for mobile is 50px.

![bannertest](https://user-images.githubusercontent.com/606764/141815854-d594bf2d-850a-48f2-9ff0-7400051ec0cc.jpg)

I'm using the following image to test.

![stock-hero-annotated](https://user-images.githubusercontent.com/606764/141816033-4761d6c1-1d7c-44c7-8a81-03d27cc35ff6.jpg)

Could you test using that image and that setting?

**Comment by katknow** [comment]
Interesting. Yeah, I'll try the different image for all of them--thanks!

**Comment by katknow** [comment]
It is definitely working with this image. I compared it to the one I was using previously and think I was just having some problems with weird dimensions/proportions. I think this is all good!

**Comment by kimisgold** [comment]
That's awesome! Could you go through the similar issues and see if they were having the same problem?

**Comment by katknow** [comment]
In process! 😄
