### ISSUE TITLE
Test configurable page blocks

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/cozy#29]
This is the theme-specific issue for omeka/omeka-s#1859. Please test this using the latest version of Omeka S on the `develop` branch.

Cozy now supports configurable resource page blocks. On a site's theme settings panel, select Cozy's "Configure resource pages" button. Test that blocks can be reordered, removed, and readded on the show views of items, media, and item sets. 

Cozy has a three block regions, all of which can coexist with each other.

* **Main (full-width)**: This sits above all other regions and takes up the full content width of the page.
* **Main (with sidebar)**: This sits below the full-width main region and inline with the right sidebar region. If it is the only populated region, it only takes up partial content width.
* **Right sidebar**: This sits to the right inline with the main with sidebar region.

**Comment by katknow** [comment]
After pulling, I'm getting this error on the front end:

 Error
Object of class Omeka\View\Helper\ResourcePageBlocks could not be converted to string

Details:

Error: Object of class Omeka\View\Helper\ResourcePageBlocks could not be converted to string in /var/www/html/katknow/OmekaSTesting/themes/cozy/view/omeka/site/item/show.phtml:10
Stack trace:
#0 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include()
#1 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#2 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#3 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#4 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#5 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#6 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#7 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#8 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#9 /var/www/html/katknow/OmekaSTesting/index.php(21): Laminas\Mvc\Application->run()
#10 {main}

**Comment by kimisgold** [comment]
@katknow Cozy was behind on a bunch of updates to the feature. It should be ready for another look.

**Comment by katknow** [comment]
This seems to be good to go now.
