### ISSUE TITLE
Media list thumbnails getting squished

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/cozy#31]
Same as in Foundation, the media list doesn't play well with with long media titles. Probably just want overflow:hidden on the titles:

![cozy-thumbnail2](https://user-images.githubusercontent.com/28012148/217357121-f9f8df92-3ea1-4fb8-8c39-e4886dca39f4.PNG)

Also, when it's full-width, the media list entries could probably use some vertical padding. This long-title one is creating space around it but the others are running up against each other:

![cozy-thumbnail](https://user-images.githubusercontent.com/28012148/217357118-65a26307-19e0-466d-9777-3565d5bc404c.PNG)

**Comment by kimisgold** [comment]
I've done some margin adjustments, with a little on top of the resource name and then a bottom margin on the whole link, thumbnail included, to provide some breathing room.

**Comment by allanaaa** [comment]
Looks great now!
