### ISSUE TITLE
.Item-resource margin-right

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/cozy#34]
.item-resource has a margin-right that I'm not sure it needs? It shows up whether the block is floated left or right. They already get margins at the block level.

<img width="1152" alt="Screenshot 2024-03-05 at 10 41 43" src="https://github.com/omeka-s-themes/cozy/assets/28012148/438dbad2-0a83-4d8d-8af7-cc875b141fb6">
<img width="456" alt="Screenshot 2024-03-05 at 10 47 10" src="https://github.com/omeka-s-themes/cozy/assets/28012148/dc7fb318-fb8c-4127-b5c6-d075328181d8">

<img width="423" alt="Screenshot 2024-03-05 at 10 43 35" src="https://github.com/omeka-s-themes/cozy/assets/28012148/9d49ee88-cd0a-470f-a31c-b1dca5a77d74">
<img width="301" alt="Screenshot 2024-03-05 at 10 43 44" src="https://github.com/omeka-s-themes/cozy/assets/28012148/68c65a18-034f-463d-95d2-a86fbd863080">

**Comment by kimisgold** [comment]
That right margin came from an assumption of multiple item attachments. I've pushed a core change that eliminates it for single item attachments.
