### ISSUE TITLE
Full-width region not showing blocks

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/cozy#35]
I don't have time to test this really thoroughly, but when I dropped a Mapping block into the item sets page full-width region, it didn't display.

<img width="992" alt="Screenshot 2024-05-14 at 12 50 00" src="https://github.com/omeka-s-themes/cozy/assets/28012148/ac081790-a0af-4d6c-a56d-74f5590d0174">

<img width="825" alt="Screenshot 2024-05-14 at 12 50 07" src="https://github.com/omeka-s-themes/cozy/assets/28012148/b9dcd082-7fa7-48fd-ae3f-d26a44da8574">

Moving it to the main-with-sidebar worked fine.

<img width="650" alt="Screenshot 2024-05-14 at 12 50 26" src="https://github.com/omeka-s-themes/cozy/assets/28012148/63bfe505-36c5-4741-97e4-6f1cfbbef1e5">
<img width="731" alt="Screenshot 2024-05-14 at 12 50 30" src="https://github.com/omeka-s-themes/cozy/assets/28012148/ddfc08bc-3827-4080-ad64-212a151baf2f">

You'll want to test other kinds of blocks in all the regions and not just on item sets.

**Comment by allanaaa** [comment]
The right sidebar isn't showing, either.

**Comment by kimisgold** [comment]
I've pushed a fix for the full width main region. Could you give me a live example for the right sidebar issue? I'm having trouble replicating that.

**Comment by allanaaa** [comment]
http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item-set/4255

Currently set up to display

<img width="825" alt="Screenshot 2024-05-17 at 12 28 58" src="https://github.com/omeka-s-themes/cozy/assets/28012148/c7e50dda-9893-4749-b724-c8aef623479d">

all of which should have content for this item set.

**Comment by kimisgold** [comment]
Ah okay, I see that it doesn't have custom markup including regions for the item set show. I'm going to check this across all the themes.

**Comment by kimisgold** [comment]
This is ready for another look.

**Comment by allanaaa** [comment]
Thanks, Cozy is showing content in all three of its regions for all three resource types now. 

Let me know if you found issues with any other themes?
