### ISSUE TITLE
Collecting form is too cozy

### ISSUE THREAD

**Issue by sheilabrennan** [omeka-s-themes/cozy#4]
![cozy-collecting](https://cloud.githubusercontent.com/assets/741484/19660045/5ba68d92-99fc-11e6-9574-b1123cd123a6.jpg)
 Firefox PC

http://dev.omeka.org/omeka-s/s/test5/page/share

**Comment by kimisgold** [comment]
This looks like an old version of the theme. The dev installation's themes are updated now, so could you refresh and see if there's improvement?

**Comment by sheilabrennan** [comment]
Ah, there is breathing room now. Better!

**Comment by sheilabrennan** [comment]
![form-cozy](https://cloud.githubusercontent.com/assets/741484/19698780/a768df38-9abe-11e6-854e-9d34629ee1b4.jpg)
