### ISSUE TITLE
Items with maps very cozy 

### ISSUE THREAD

**Issue by alyssafahringer** [omeka-s-themes/cozy#6]
I'm not sure if this is an issue, but wanted to make sure the map block is supposed to display this way on an item page: 

![screen shot 2016-10-24 at 3 18 19 pm](https://cloud.githubusercontent.com/assets/8807816/19660296/27843770-99fd-11e6-8588-6a0c2f676a91.png)

![screen shot 2016-10-24 at 3 18 32 pm](https://cloud.githubusercontent.com/assets/8807816/19660297/2784b8a8-99fd-11e6-9fc1-ab497761f652.png)

**Comment by sheilabrennan** [comment]
Getting similar display of the map on the item-show pages on FFX for PC...and the property names are wrapping to the next line, leaving terrible orphans who were cozied out of the row.
![item-show-map-cozy](https://cloud.githubusercontent.com/assets/741484/19663349/8822d544-9a09-11e6-985f-04775b34c97d.jpg)

**Comment by kimisgold** [comment]
Fixed in b5fdabe17567040e14b2bb13197641e253568277.
