### ISSUE TITLE
Logo Upload shifts Nav Menu bar in header

### ISSUE THREAD

**Issue by sheilabrennan** [omeka-s-themes/cozy#8]
![cozy-nav-with-logo](https://cloud.githubusercontent.com/assets/741484/19661334/46fd660e-9a01-11e6-9f1b-42e40c110f40.jpg)

The boxes don't quite line up in a noticeable way.

**Comment by kimisgold** [comment]
Fixed in 0a98320027dc4192afc8492917bd6f2984f1cae8.
